version: '3.4'

services:
  nextjs:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=prisma
