import { ReactNode } from 'react';
import Head from 'next/head';
import { Navigation } from './Navigation';

const MainLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap"
        />
      </Head>
      <div className="min-h-screen flex">
        <Navigation />
        <main className="flex flex-1">{children}</main>
      </div>
    </>
  );
};

export default MainLayout;
